[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  publish = "/src/_site"
  port = 3000
  targetPort = 8080
  framework = "#custom"
  NODE_ENV = "development"
  autoLaunch = true
